export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_CHANGE_EMAIL = 'AUTH_CHANGE_EMAIL'
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOADING = 'AUTH_LOADING'

export const USERPROFILE_LOADING = 'USERPROFILE_LOADING'
export const USERPROFILE_SHOWDATA = 'USERPROFILE_SHOWDATA'
export const USERPROFILE_ERROR = 'USERPROFILE_ERROR'

export const HOTELS_LOADING = 'HOTELS_LOADING'
export const HOTELS_SHOWDATA = 'HOTELS_SHOWDATA'
export const HOTELS_ERROR = 'HOTELS_ERROR'

export const DETAIL_HOTEL_LOADING = 'DETAIL_HOTEL_LOADING'
export const DETAIL_HOTEL_SHOWDATA = 'DETAIL_HOTEL_SHOWDATA'
export const DETAIL_HOTEL_ERROR = 'DETAIL_HOTEL_ERROR'

export const ON_SET_FILTER_CITYNAME = 'ON_SET_FILTER_CITYNAME'
export const ON_SET_FILTER_DATE = 'ON_SET_FILTER_DATE'
export const ON_SET_NEWSTARTDATEFORMAT = 'ON_SET_NEWSTARTDATEFORMAT'
export const ON_SET_NEWENDDATEFORMAT = 'ON_SET_NEWENDDATEFORMAT'

export const BOOKING_LOADING = 'BOOKING_LOADING'
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS'
export const BOOKING_ERROR = 'BOOKING_ERROR'

export const MYBOOKINGS_LOADING = 'MYBOOKINGS_LOADING'
export const MYBOOKINGS_SHOWDATA = 'MYBOOKINGS_SHOWDATA'
export const MYBOOKINGS_ERROR = 'MYBOOKINGS_ERROR'